export type CityPlace = {
  name: string;
  slug: string;
  state?: string;
  region: string;
  famousFood: string;
  seoDescription: string;
};

export const cityPlaces: CityPlace[] = [
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    region: "India",
    famousFood: "Vada pav, pav bhaji, bhel puri, and Bombay sandwich",
    seoDescription:
      "Mumbai is famous for street food favorites like vada pav, pav bhaji, bhel puri, and Bombay sandwich, making it one of India's most loved food cities.",
  },
  {
    name: "Delhi",
    slug: "delhi",
    state: "Delhi",
    region: "India",
    famousFood: "Chole bhature, parathas, kebabs, and chaat",
    seoDescription:
      "Delhi is known for chole bhature, stuffed parathas, flavorful kebabs, and tangy chaat found in old city lanes and modern markets across the capital.",
  },
  {
    name: "Bengaluru",
    slug: "bengaluru",
    state: "Karnataka",
    region: "India",
    famousFood: "Masala dosa, idli, filter coffee, and bisi bele bath",
    seoDescription:
      "Bengaluru is famous for masala dosa, soft idli, strong filter coffee, and bisi bele bath, blending South Indian comfort food with a lively cafe culture.",
  },
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    region: "India",
    famousFood: "Kathi rolls, rosogolla, mishti doi, and fish curry",
    seoDescription:
      "Kolkata is famous for kathi rolls, rosogolla, mishti doi, and fish curry, making it one of India's richest cities for sweets and street food.",
  },
  {
    name: "Chennai",
    slug: "chennai",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Idli, dosa, pongal, filter coffee, and seafood",
    seoDescription:
      "Chennai is known for idli, dosa, pongal, strong filter coffee, and coastal seafood dishes that showcase the city's deep South Indian food traditions.",
  },
  {
    name: "Hyderabad",
    slug: "hyderabad",
    state: "Telangana",
    region: "India",
    famousFood: "Hyderabadi biryani, haleem, kebabs, and double ka meetha",
    seoDescription:
      "Hyderabad is famous for its aromatic biryani, rich haleem, juicy kebabs, and sweets like double ka meetha, giving the city a strong culinary identity.",
  },
  {
    name: "Pune",
    slug: "pune",
    state: "Maharashtra",
    region: "India",
    famousFood: "Misal pav, vada pav, bhakarwadi, and mastani",
    seoDescription:
      "Pune is famous for misal pav, vada pav, bhakarwadi, and mastani, with a street food culture loved by students and locals alike.",
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "India",
    famousFood: "Dal baati churma, ghewar, kachori, and laal maas",
    seoDescription:
      "Jaipur is known for dal baati churma, sweet ghewar, kachori, and spicy laal maas, giving the city a distinct Rajasthani food identity.",
  },
  {
    name: "Ahmedabad",
    slug: "ahmedabad",
    state: "Gujarat",
    region: "India",
    famousFood: "Dhokla, fafda, jalebi, and Gujarati thali",
    seoDescription:
      "Ahmedabad is famous for dhokla, fafda, jalebi, and the traditional Gujarati thali, making it a standout city for vegetarian food lovers.",
  },
  {
    name: "Surat",
    slug: "surat",
    state: "Gujarat",
    region: "India",
    famousFood: "Locho, khaman, sev khamani, and surti ghari",
    seoDescription:
      "Surat is well known for locho, khaman, sev khamani, and surti ghari, with a snack-rich food culture that keeps the city buzzing.",
  },
  {
    name: "Lucknow",
    slug: "lucknow",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Tunday kebab, biryani, sheermal, and kulfi",
    seoDescription:
      "Lucknow is famous for Tunday kebabs, fragrant biryani, sheermal, and kulfi, reflecting its refined Awadhi culinary tradition.",
  },
  {
    name: "Kanpur",
    slug: "kanpur",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Chaat, samosa, kachori, and thandai",
    seoDescription:
      "Kanpur is known for chaat, samosa, kachori, and thandai, with busy markets and local stalls offering simple but flavorful food.",
  },
  {
    name: "Nagpur",
    slug: "nagpur",
    state: "Maharashtra",
    region: "India",
    famousFood: "Saoji curry, tarri poha, oranges, and samosas",
    seoDescription:
      "Nagpur is famous for spicy Saoji curry, tarri poha, oranges, and samosas, creating a strong and memorable local food identity.",
  },
  {
    name: "Indore",
    slug: "indore",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Poha jalebi, bhutte ka kees, garadu, and chaat",
    seoDescription:
      "Indore is famous for poha jalebi, bhutte ka kees, garadu, and chaat, making it one of India's most beloved street food destinations.",
  },
  {
    name: "Patna",
    slug: "patna",
    state: "Bihar",
    region: "India",
    famousFood: "Litti chokha, sattu paratha, tilkut, and khaja",
    seoDescription:
      "Patna is known for litti chokha, sattu paratha, tilkut, and khaja, showcasing the rich and rustic flavors of Bihar.",
  },
  {
    name: "Bhopal",
    slug: "bhopal",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Biryani, kebabs, poha, and bhutte ka kees",
    seoDescription:
      "Bhopal blends royal and everyday flavors, with biryani, kebabs, poha, and bhutte ka kees among its most famous foods.",
  },
  {
    name: "Coimbatore",
    slug: "coimbatore",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Idli, dosa, biryani, and street filter coffee",
    seoDescription:
      "Coimbatore is known for idli, dosa, biryani, and strong filter coffee, offering the comforting flavors of Tamil Nadu cuisine.",
  },
  {
    name: "Kochi",
    slug: "kochi",
    state: "Kerala",
    region: "India",
    famousFood: "Appam, seafood curry, puttu, and banana chips",
    seoDescription:
      "Kochi is famous for appam, seafood curry, puttu, and banana chips, with coastal Kerala flavors shaping the city's food identity.",
  },
  {
    name: "Mysuru",
    slug: "mysuru",
    state: "Karnataka",
    region: "India",
    famousFood: "Mysore pak, dosa, idli, and bisibele bath",
    seoDescription:
      "Mysuru is known for Mysore pak, dosa, idli, and bisibele bath, offering a royal South Indian food experience with classic sweets and comfort meals.",
  },
  {
    name: "Madurai",
    slug: "madurai",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Jigarthanda, parotta, kari dosai, and idiyappam",
    seoDescription:
      "Madurai is famous for jigarthanda, flaky parotta, kari dosai, and idiyappam, making it one of Tamil Nadu's most iconic food cities.",
  },
  {
    name: "Thiruvananthapuram",
    slug: "thiruvananthapuram",
    state: "Kerala",
    region: "India",
    famousFood: "Puttu, kadala curry, appam, and fish curry",
    seoDescription:
      "Thiruvananthapuram is known for puttu, kadala curry, appam, and fish curry, highlighting the traditional flavors of Kerala cuisine.",
  },
  {
    name: "Visakhapatnam",
    slug: "visakhapatnam",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Bongu chicken, fish fry, punugulu, and prawn curry",
    seoDescription:
      "Visakhapatnam is famous for bongu chicken, fish fry, punugulu, and prawn curry, with coastal Andhra flavors shaping the local food scene.",
  },
  {
    name: "Bhubaneswar",
    slug: "bhubaneswar",
    state: "Odisha",
    region: "India",
    famousFood: "Dalma, chhena poda, pakhala bhata, and bara ghuguni",
    seoDescription:
      "Bhubaneswar is known for dalma, chhena poda, pakhala bhata, and bara ghuguni, offering a strong taste of Odia traditional food.",
  },
  {
    name: "Chandigarh",
    slug: "chandigarh",
    state: "Chandigarh",
    region: "India",
    famousFood: "Chole bhature, butter chicken, paneer tikka, and lassi",
    seoDescription:
      "Chandigarh is famous for chole bhature, butter chicken, paneer tikka, and lassi, reflecting the rich North Indian food culture of the region.",
  },
  {
    name: "Amritsar",
    slug: "amritsar",
    state: "Punjab",
    region: "India",
    famousFood: "Amritsari kulcha, chole, lassi, and fish fry",
    seoDescription:
      "Amritsar is famous for Amritsari kulcha, spicy chole, creamy lassi, and crisp fish fry, making it a top destination for Punjabi food lovers.",
  },
  {
    name: "Jodhpur",
    slug: "jodhpur",
    state: "Rajasthan",
    region: "India",
    famousFood: "Makhaniya lassi, mirchi vada, pyaaz kachori, and dal bati",
    seoDescription:
      "Jodhpur is known for makhaniya lassi, mirchi vada, pyaaz kachori, and dal bati, giving the Blue City its signature Rajasthani flavors.",
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "India",
    famousFood: "Dal baati churma, gatte ki sabzi, kachori, and ghevar",
    seoDescription:
      "Udaipur is famous for dal baati churma, gatte ki sabzi, kachori, and ghevar, offering a rich and royal Rajasthani dining experience.",
  },
  {
    name: "Ranchi",
    slug: "ranchi",
    state: "Jharkhand",
    region: "India",
    famousFood: "Litti chokha, dhuska, chilka roti, and bamboo shoot dishes",
    seoDescription:
      "Ranchi is known for litti chokha, dhuska, chilka roti, and bamboo shoot dishes, showcasing the rustic flavors of Jharkhand cuisine.",
  },
  {
    name: "Raipur",
    slug: "raipur",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Chila, fara, muthiya, and amti",
    seoDescription:
      "Raipur is famous for chila, fara, muthiya, and amti, giving visitors a taste of traditional Chhattisgarhi food.",
  },
  {
    name: "Dehradun",
    slug: "dehradun",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Bal mithai, aloo ke gutke, momos, and singori",
    seoDescription:
      "Dehradun is known for bal mithai, aloo ke gutke, momos, and singori, combining hill-state sweets with popular local snacks.",
  },
  {
    name: "Srinagar",
    slug: "srinagar",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Rogan josh, yakhni, kahwa, and wazwan dishes",
    seoDescription:
      "Srinagar is famous for rogan josh, yakhni, kahwa, and traditional wazwan dishes, reflecting the rich culinary heritage of Kashmir.",
  },
  {
    name: "Shimla",
    slug: "shimla",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Madra, siddu, chana madra, and fruit chaat",
    seoDescription:
      "Shimla is known for madra, siddu, chana madra, and fruit chaat, bringing the flavors of Himachal Pradesh to the hill station table.",
  },
  {
    name: "Gwalior",
    slug: "gwalior",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Bedai, jalebi, kachori, and poha",
    seoDescription:
      "Gwalior is famous for bedai, jalebi, kachori, and poha, making it a strong stop for classic North Indian breakfast and snack food.",
  },
  {
    name: "Varanasi",
    slug: "varanasi",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Kachori sabzi, tamatar chaat, malaiyyo, and lassi",
    seoDescription:
      "Varanasi is famous for kachori sabzi, tamatar chaat, malaiyyo, and lassi, with its street food culture deeply tied to the city's heritage.",
  },
  {
    name: "Agra",
    slug: "agra",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Petha, bedai, dalmoth, and chaat",
    seoDescription:
      "Agra is known for petha, bedai, dalmoth, and chaat, offering visitors sweet and savory specialties beyond its famous monuments.",
  },
  {
    name: "Ludhiana",
    slug: "ludhiana",
    state: "Punjab",
    region: "India",
    famousFood: "Butter chicken, paneer tikka, lassi, and parathas",
    seoDescription:
      "Ludhiana is famous for butter chicken, paneer tikka, lassi, and parathas, reflecting the hearty and rich flavors of Punjab.",
  },
  {
    name: "Jalandhar",
    slug: "jalandhar",
    state: "Punjab",
    region: "India",
    famousFood: "Amritsari kulcha, chole, tikki, and lassi",
    seoDescription:
      "Jalandhar is known for Amritsari kulcha, chole, tikki, and lassi, with strong Punjabi flavors that make the city a food favorite.",
  },
  {
    name: "Mangalore",
    slug: "mangalore",
    state: "Karnataka",
    region: "India",
    famousFood: "Mangalore bun, fish curry, neer dosa, and ghee roast",
    seoDescription:
      "Mangalore is famous for Mangalore bun, fish curry, neer dosa, and ghee roast, showcasing the coastal cuisine of Karnataka.",
  },
  {
    name: "Kozhikode",
    slug: "kozhikode",
    state: "Kerala",
    region: "India",
    famousFood: "Kallummakkaya, biryani, halwa, and pathiri",
    seoDescription:
      "Kozhikode is known for biryani, halwa, pathiri, and Kallummakkaya, making it one of Kerala's most celebrated food destinations.",
  },
  {
    name: "Thrissur",
    slug: "thrissur",
    state: "Kerala",
    region: "India",
    famousFood: "Puttu, kadala curry, palada pradhaman, and fish curry",
    seoDescription:
      "Thrissur is famous for puttu, kadala curry, palada pradhaman, and fish curry, offering a true taste of Kerala hospitality.",
  },
  {
    name: "Tiruchirappalli",
    slug: "tiruchirappalli",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Sambar, idli, dosa, and kavuni rice",
    seoDescription:
      "Tiruchirappalli is known for sambar, idli, dosa, and kavuni rice, bringing traditional Tamil food to the forefront.",
  },
  {
    name: "Salem",
    slug: "salem",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Kongunadu biryani, idiyappam, and spicy gravies",
    seoDescription:
      "Salem is famous for Kongunadu biryani, idiyappam, and spicy gravies, reflecting the bold flavors of western Tamil Nadu.",
  },
  {
    name: "Tirupati",
    slug: "tirupati",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Laddu, pulihora, dosa, and vada",
    seoDescription:
      "Tirupati is famous for its laddu, pulihora, dosa, and vada, with temple food traditions playing a big role in the city's identity.",
  },
  {
    name: "Panaji",
    slug: "panaji",
    state: "Goa",
    region: "India",
    famousFood: "Goan fish curry, bebinca, xacuti, and cafreal",
    seoDescription:
      "Panaji is known for Goan fish curry, bebinca, xacuti, and cafreal, offering classic coastal flavors from the heart of Goa.",
  },
  {
    name: "Nashik",
    slug: "nashik",
    state: "Maharashtra",
    region: "India",
    famousFood: "Misal pav, sabudana vada, thalipeeth, and grapes",
    seoDescription:
      "Nashik is famous for misal pav, sabudana vada, thalipeeth, and grapes, with a food culture rooted in Maharashtra's comforting flavors.",
  },
  {
    name: "Guwahati",
    slug: "guwahati",
    state: "Assam",
    region: "India",
    famousFood: "Pitha, masor tenga, bamboo shoot dishes, and laru",
    seoDescription:
      "Guwahati is known for pitha, masor tenga, bamboo shoot dishes, and laru, offering a strong introduction to Assamese cuisine.",
  },
  {
    name: "Siliguri",
    slug: "siliguri",
    state: "West Bengal",
    region: "India",
    famousFood: "Momos, thukpa, phuchka, and tea snacks",
    seoDescription:
      "Siliguri is famous for momos, thukpa, phuchka, and tea snacks, reflecting its Himalayan influence and bustling food culture.",
  },
  {
    name: "Noida",
    slug: "noida",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Street momos, chaat, rolls, and North Indian meals",
    seoDescription:
      "Noida is known for street momos, chaat, rolls, and North Indian meals, with a modern food scene that serves workers and families alike.",
  },
  {
    name: "Gurugram",
    slug: "gurugram",
    state: "Haryana",
    region: "India",
    famousFood: "Butter chicken, rolls, biryani, and cafe food",
    seoDescription:
      "Gurugram is famous for butter chicken, rolls, biryani, and cafe food, making it one of the most popular dining hubs in the Delhi NCR region.",
  },
  {
    name: "Faridabad",
    slug: "faridabad",
    state: "Haryana",
    region: "India",
    famousFood: "Chaat, tandoori snacks, parathas, and sweets",
    seoDescription:
      "Faridabad is known for chaat, tandoori snacks, parathas, and sweets, giving the city a simple but popular food identity.",
  },
  {
    name: "Port Blair",
    slug: "port-blair",
    state: "Andaman and Nicobar Islands",
    region: "India",
    famousFood: "Seafood platter, fish curry, crab masala, and lobster",
    seoDescription: "Port Blair is famous for fresh coastal seafood, crab masala, and tropical island delicacies.",
  },
  {
    name: "Havelock Island",
    slug: "havelock-island",
    state: "Andaman and Nicobar Islands",
    region: "India",
    famousFood: "Grilled fish, tiger prawns, and fresh coconut water",
    seoDescription: "Havelock Island offers seaside dining with freshly caught grilled fish and island seafood specials.",
  },
  {
    name: "Diglipur",
    slug: "diglipur",
    state: "Andaman and Nicobar Islands",
    region: "India",
    famousFood: "Local fish curry, rice meals, and tropical fruits",
    seoDescription: "Diglipur is known for fresh local fish curries and rustic island home-style cuisine.",
  },
  {
    name: "Amaravati",
    slug: "amaravati",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Gongura pachadi, Andhra meals, and pesarattu",
    seoDescription: "Amaravati is known for traditional Andhra cuisine featuring spicy gongura and rich lentil dishes.",
  },
  {
    name: "Vijayawada",
    slug: "vijayawada",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Pulihora, punugulu, chicken fry, and mirchi bajji",
    seoDescription: "Vijayawada is famous for spicy street food like punugulu, fiery mirchi bajji, and traditional Andhra biryani.",
  },
  {
    name: "Guntur",
    slug: "guntur",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Guntur mirchi curry, gongura mutton, and spicy idli",
    seoDescription: "Guntur is world-renowned for fiery chillies that define signature spicy curries and chutneys.",
  },
  {
    name: "Nellore",
    slug: "nellore",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Nellore chepala pulusu, malai khaja, and seafood curry",
    seoDescription: "Nellore is celebrated for its iconic tangy chepala pulusu fish curry and traditional sweets.",
  },
  {
    name: "Kurnool",
    slug: "kurnool",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Ugadi pachadi, rayalaseema ragi mudda, and jowar roti",
    seoDescription: "Kurnool showcases hearty Rayalaseema cuisine with ragi mudda, spicy natukodi chicken, and jowar rotis.",
  },
  {
    name: "Kakinada",
    slug: "kakinada",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Kakinada kaja, subbaiah gari hotel meals, and seafood",
    seoDescription: "Kakinada is famous for its sweet Kakinada kaja and coastal Andhra vegetarian and seafood feasts.",
  },
  {
    name: "Rajahmundry",
    slug: "rajahmundry",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Pootharekulu, pulasa fish curry, and rose milk",
    seoDescription: "Rajahmundry is known for paper-thin pootharekulu sweets, rare seasonal pulasa fish, and rich rose milk.",
  },
  {
    name: "Kadapa",
    slug: "kadapa",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Ragi sankati, natukodi pulusu, and karam dosa",
    seoDescription: "Kadapa is loved for rustic Rayalaseema flavors including ragi sankati and spicy country chicken gravy.",
  },
  {
    name: "Anantapur",
    slug: "anantapur",
    state: "Andhra Pradesh",
    region: "India",
    famousFood: "Jowar roti, gongura chicken, and obbattu",
    seoDescription: "Anantapur features wholesome millet dishes, spicy gongura gravies, and festive sweet obbattu.",
  },
  {
    name: "Itanagar",
    slug: "itanagar",
    state: "Arunachal Pradesh",
    region: "India",
    famousFood: "Thukpa, boiled pork with bamboo shoots, momos, and apong",
    seoDescription: "Itanagar offers authentic tribal cuisine prepared with aromatic herbs, smoked meats, and tender bamboo shoots.",
  },
  {
    name: "Naharlagun",
    slug: "naharlagun",
    state: "Arunachal Pradesh",
    region: "India",
    famousFood: "Momos, noodle soup, pork curry, and herbal teas",
    seoDescription: "Naharlagun is known for comforting Himalayan broth, steamed dumplings, and indigenous herbal flavors.",
  },
  {
    name: "Pasighat",
    slug: "pasighat",
    state: "Arunachal Pradesh",
    region: "India",
    famousFood: "Smoked fish, boiled leafy greens, and sticky rice",
    seoDescription: "Pasighat on the banks of the Siang river highlights organic river fish and wild herbs.",
  },
  {
    name: "Tawang",
    slug: "tawang",
    state: "Arunachal Pradesh",
    region: "India",
    famousFood: "Zan, gyapa khazi, momos, and butter tea",
    seoDescription: "Tawang is famous for warming Monpa dishes like zan porridge, cheese broth, and authentic Tibetan butter tea.",
  },
  {
    name: "Ziro",
    slug: "ziro",
    state: "Arunachal Pradesh",
    region: "India",
    famousFood: "Pike pila, smoked pork with bamboo, and rice beer",
    seoDescription: "Ziro is celebrated for Apatani culinary heritage featuring organic smoked meats, bamboo shoot delicacies, and rice beer.",
  },
  {
    name: "Dispur",
    slug: "dispur",
    state: "Assam",
    region: "India",
    famousFood: "Masor tenga, khaar, pithas, and duck curry",
    seoDescription: "Dispur serves refined Assamese culinary classics including tangy fish curries and traditional festive pithas.",
  },
  {
    name: "Silchar",
    slug: "silchar",
    state: "Assam",
    region: "India",
    famousFood: "Shorshe ilish, shutki chutney, and pitha",
    seoDescription: "Silchar blends Barak Valley Bengali and Assamese traditions with mustard fish curries and savory chutneys.",
  },
  {
    name: "Dibrugarh",
    slug: "dibrugarh",
    state: "Assam",
    region: "India",
    famousFood: "Assam tea, duck meat curry, and bamboo shoot fry",
    seoDescription: "Dibrugarh in the tea heartland is famous for aromatic CTC and orthodox teas paired with hearty regional curries.",
  },
  {
    name: "Jorhat",
    slug: "jorhat",
    state: "Assam",
    region: "India",
    famousFood: "Pani pitha, sunga saul, and pork with lai xaak",
    seoDescription: "Jorhat is recognized for traditional bamboo-steamed sunga rice and flavorful mustard green pork dishes.",
  },
  {
    name: "Nagaon",
    slug: "nagaon",
    state: "Assam",
    region: "India",
    famousFood: "Rohu fish curry, boror tenga, and jolpan",
    seoDescription: "Nagaon is known for central Assam agrarian flavors, crispy lentil fritter curries, and comforting breakfast jolpan.",
  },
  {
    name: "Tinsukia",
    slug: "tinsukia",
    state: "Assam",
    region: "India",
    famousFood: "Pork dry fry, tea garden snacks, and smoked meats",
    seoDescription: "Tinsukia offers a rich mix of tribal and tea garden food traditions with fragrant spices and smoked preparations.",
  },
  {
    name: "Tezpur",
    slug: "tezpur",
    state: "Assam",
    region: "India",
    famousFood: "Chital fish curry, Jolpan, and bamboo shoot pickle",
    seoDescription: "Tezpur on the Brahmaputra is celebrated for freshwater fish feasts, festive curd and beaten rice, and tangy pickles.",
  },
  {
    name: "Gaya",
    slug: "gaya",
    state: "Bihar",
    region: "India",
    famousFood: "Tilkat, anarsa, litti chokha, and kesaria peda",
    seoDescription: "Gaya is renowned across India for sesame tilkut, crispy anarsa sweets, and comforting charcoal-roasted litti chokha.",
  },
  {
    name: "Bhagalpur",
    slug: "bhagalpur",
    state: "Bihar",
    region: "India",
    famousFood: "Katarni chura, litti chokha, and silk city sweets",
    seoDescription: "Bhagalpur is acclaimed for fragrant Katarni aromatic flattened rice and classic Bihari sweet dishes.",
  },
  {
    name: "Muzaffarpur",
    slug: "muzaffarpur",
    state: "Bihar",
    region: "India",
    famousFood: "Shahi litchi, litti chokha, and sattu drink",
    seoDescription: "Muzaffarpur is globally famous for juicy Shahi litchis, wholesome sattu refreshments, and traditional litti.",
  },
  {
    name: "Purnia",
    slug: "purnia",
    state: "Bihar",
    region: "India",
    famousFood: "Sattu paratha, litti chokha, and freshwater fish",
    seoDescription: "Purnia in eastern Bihar offers hearty sattu stuffed breads and fresh riverine culinary specialties.",
  },
  {
    name: "Darbhanga",
    slug: "darbhanga",
    state: "Bihar",
    region: "India",
    famousFood: "Makhana kheer, machh-bhaat, and thekua",
    seoDescription: "Darbhanga is the capital of Mithila cuisine featuring fox nut (makhana) delicacies, mustard fish, and festive thekua.",
  },
  {
    name: "Bihar Sharif",
    slug: "bihar-sharif",
    state: "Bihar",
    region: "India",
    famousFood: "Khaja, sattu ghol, and litti chokha",
    seoDescription: "Bihar Sharif and nearby Nalanda are renowned for multi-layered crisp khaja sweets and savory sattu preparations.",
  },
  {
    name: "Arrah",
    slug: "arrah",
    state: "Bihar",
    region: "India",
    famousFood: "Litti chokha, chana ghugni, and malpua",
    seoDescription: "Arrah features robust Bhojpur flavors including spicy black gram ghugni and sweet festival malpuas.",
  },
  {
    name: "Begusarai",
    slug: "begusarai",
    state: "Bihar",
    region: "India",
    famousFood: "Litti chokha, dahi chura, and dal pitha",
    seoDescription: "Begusarai offers authentic dairy-rich dahi chura, steamed rice flour pithas, and roadside litti.",
  },
  {
    name: "Bilaspur",
    slug: "bilaspur",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Doobraj rice, chila, fara, and samosa",
    seoDescription: "Bilaspur is celebrated for scented Doobraj rice, rice flour chila crepes, and savory steamed fara.",
  },
  {
    name: "Bhilai",
    slug: "bhilai",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Fara, bhajiya, samosa chaat, and jalebi",
    seoDescription: "Bhilai combines cosmopolitan steel city food stalls with authentic Chhattisgarhi street snacks.",
  },
  {
    name: "Durg",
    slug: "durg",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Chila, thetthari, and khurmi",
    seoDescription: "Durg is known for crunchy festival savory snacks like thetthari and traditional rice-lentil delicacies.",
  },
  {
    name: "Korba",
    slug: "korba",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Bafauri, muthiya, and red ant chutney",
    seoDescription: "Korba showcases nutritious steamed chana dal bafauri and unique tribal culinary traditions.",
  },
  {
    name: "Rajnandgaon",
    slug: "rajnandgaon",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Petha, fara, and kadi pakora",
    seoDescription: "Rajnandgaon offers soothing rural Chhattisgarhi flavors with rice snacks and tangy buttermilk gravies.",
  },
  {
    name: "Jagdalpur",
    slug: "jagdalpur",
    state: "Chhattisgarh",
    region: "India",
    famousFood: "Mahua syrup, chaprah chutney, and millet roti",
    seoDescription: "Jagdalpur in Bastar offers rich indigenous food culture centered around millets, wild forest herbs, and seasonal specialties.",
  },
  {
    name: "Daman",
    slug: "daman",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    region: "India",
    famousFood: "Goan-Portuguese fish curry, chicken xacuti, and seafood",
    seoDescription: "Daman blends Portuguese coastal culinary heritage with fresh Arabian sea fish and prawn curries.",
  },
  {
    name: "Silvassa",
    slug: "silvassa",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    region: "India",
    famousFood: "Ubadiyu, wild mushroom curry, and tribal roti",
    seoDescription: "Silvassa is famous for clay-pot roasted ubadiyu and earthen tribal delicacies surrounded by lush forests.",
  },
  {
    name: "Diu",
    slug: "diu",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    region: "India",
    famousFood: "Lobster, calamari, fish fry, and Portuguese bread",
    seoDescription: "Diu island is renowned for peaceful coastal dining with fresh lobsters, calamari, and seaside drinks.",
  },
  {
    name: "Margao",
    slug: "margao",
    state: "Goa",
    region: "India",
    famousFood: "Goan sausage pav, fish thali, bebinca, and sorpotel",
    seoDescription: "Margao is South Goa's cultural food capital famous for spicy chourico pork sausage and authentic beachside fish thalis.",
  },
  {
    name: "Vasco da Gama",
    slug: "vasco-da-gama",
    state: "Goa",
    region: "India",
    famousFood: "Rava fish fry, prawn balchao, and poi bread",
    seoDescription: "Vasco da Gama offers coastal harbor food featuring semolina-crusted fish fry and warm Goan poi bread.",
  },
  {
    name: "Mapusa",
    slug: "mapusa",
    state: "Goa",
    region: "India",
    famousFood: "Spicy xacuti, mirchi bajji, and traditional sweets",
    seoDescription: "Mapusa is famous for its Friday market packed with home-ground spices, dried fish, and local bakery goods.",
  },
  {
    name: "Ponda",
    slug: "ponda",
    state: "Goa",
    region: "India",
    famousFood: "Hindu Goan vegetarian thali, khatkhate, and solkadhi",
    seoDescription: "Ponda is known for Goan temple cuisine featuring coconut-based vegetable khatkhate and digestive solkadhi.",
  },
  {
    name: "Gandhinagar",
    slug: "gandhinagar",
    state: "Gujarat",
    region: "India",
    famousFood: "Dhokla, thepla, Gujarati thali, and khichdi",
    seoDescription: "Gandhinagar features wholesome Gujarati thalis with sweet-sour dals, seasonal vegetables, and warm phulkas.",
  },
  {
    name: "Vadodara",
    slug: "vadodara",
    state: "Gujarat",
    region: "India",
    famousFood: "Sev usal, kachori, bhakarwadi, and lilo chevdo",
    seoDescription: "Vadodara is famous for spicy street sev usal, flavorful Mahakali kachoris, and authentic Gujarati namkeens.",
  },
  {
    name: "Rajkot",
    slug: "rajkot",
    state: "Gujarat",
    region: "India",
    famousFood: "Kathiyawadi thali, ringna no olo, and peda",
    seoDescription: "Rajkot is the heart of Kathiyawadi cuisine renowned for smoky roasted eggplant olo and melt-in-mouth Peda sweets.",
  },
  {
    name: "Bhavnagar",
    slug: "bhavnagar",
    state: "Gujarat",
    region: "India",
    famousFood: "Bhavnagari gathiya, pav gathiya, and peda",
    seoDescription: "Bhavnagar is world-famous for soft and peppery Bhavnagari gathiya, street pav-gathiya, and traditional sweets.",
  },
  {
    name: "Jamnagar",
    slug: "jamnagar",
    state: "Gujarat",
    region: "India",
    famousFood: "Ghughra, dry fruit kachori, and katarmal sweets",
    seoDescription: "Jamnagar offers crispy fried ghughra with tangy chutneys and rich dry fruit stuffed savory kachoris.",
  },
  {
    name: "Junagadh",
    slug: "junagadh",
    state: "Gujarat",
    region: "India",
    famousFood: "Kathiyawadi dhokli nu shaak, rotla, and kesar mango",
    seoDescription: "Junagadh at the foothills of Girnar is loved for hearty bajra rotlas, garlic chutneys, and world-class Kesar mangoes.",
  },
  {
    name: "Anand",
    slug: "anand",
    state: "Gujarat",
    region: "India",
    famousFood: "Amul butter snacks, cheese paratha, and dahi puri",
    seoDescription: "Anand, the milk capital of India, is famous for dairy-rich specialties, buttery street food, and traditional sweets.",
  },
  {
    name: "Navsari",
    slug: "navsari",
    state: "Gujarat",
    region: "India",
    famousFood: "Parsi dhansak, patra ni machhi, and sweet surti ghari",
    seoDescription: "Navsari boasts a historic Parsi culinary heritage alongside classic South Gujarat vegetarian dishes.",
  },
  {
    name: "Morbi",
    slug: "morbi",
    state: "Gujarat",
    region: "India",
    famousFood: "Khaman, fafda, and Saurashtra street food",
    seoDescription: "Morbi offers vibrant Saurashtra snack culture with hot morning jalebi-fafda and tea stall gatherings.",
  },
  {
    name: "Vapi",
    slug: "vapi",
    state: "Gujarat",
    region: "India",
    famousFood: "Undhiyu, locho, and street rolls",
    seoDescription: "Vapi serves authentic winter undhiyu casseroles, steaming locho, and buzzing border-town street foods.",
  },
  {
    name: "Panipat",
    slug: "panipat",
    state: "Haryana",
    region: "India",
    famousFood: "Pachranga pickle, bajra khichdi, and kadhi pakora",
    seoDescription: "Panipat is famous for world-renowned Pachranga pickles and traditional Haryanvi rustic bajra porridge.",
  },
  {
    name: "Ambala",
    slug: "ambala",
    state: "Haryana",
    region: "India",
    famousFood: "Tandoori chicken, parathas, and jalebi",
    seoDescription: "Ambala offers bustling cantt food joints, crisp morning tandoori parathas, and gigantic syrup-filled jalebis.",
  },
  {
    name: "Yamunanagar",
    slug: "yamunanagar",
    state: "Haryana",
    region: "India",
    famousFood: "Chaat, malai chaap, and dal makhani",
    seoDescription: "Yamunanagar is known for roadside North Indian delicacies, creamy tandoori chaap, and slow-cooked lentils.",
  },
  {
    name: "Rohtak",
    slug: "rohtak",
    state: "Haryana",
    region: "India",
    famousFood: "Rewari, gajak, desi ghee parathas, and lassi",
    seoDescription: "Rohtak is celebrated for winter sesame rewari sweets, crispy gajak, and heavy country-style ghee parathas.",
  },
  {
    name: "Hisar",
    slug: "hisar",
    state: "Haryana",
    region: "India",
    famousFood: "Peda, kachori, and dahi bhalla",
    seoDescription: "Hisar is famous for dairy-fresh Dudh Peda sweets, spicy morning kachoris, and chilled sweet curd chaat.",
  },
  {
    name: "Karnal",
    slug: "karnal",
    state: "Haryana",
    region: "India",
    famousFood: "Basmati rice dishes, rajma chawal, and malai kulfi",
    seoDescription: "Karnal in the Basmati rice belt is known for aromatic rice meals, highway dhaba curries, and rich kulfis.",
  },
  {
    name: "Sonipat",
    slug: "sonipat",
    state: "Haryana",
    region: "India",
    famousFood: "Murthal parathas, white butter, and sweet lassi",
    seoDescription: "Sonipat, home to the legendary Murthal highway corridor, is famous for tandoori parathas served with mountains of white butter.",
  },
  {
    name: "Panchkula",
    slug: "panchkula",
    state: "Haryana",
    region: "India",
    famousFood: "Chole kulche, paneer tikka, and cafe specialties",
    seoDescription: "Panchkula offers modern Tri-city dining alongside popular North Indian comfort foods and street chaats.",
  },
  {
    name: "Bahadurgarh",
    slug: "bahadurgarh",
    state: "Haryana",
    region: "India",
    famousFood: "Chaat, samosa, and highway dal tadka",
    seoDescription: "Bahadurgarh on the Delhi-Haryana border is loved for spicy tea-time samosas and highway dhabas.",
  },
  {
    name: "Dharamshala",
    slug: "dharamshala",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Tibetan momos, thukpa, thenthuk, and kangri dham",
    seoDescription: "Dharamshala blends Tibetan street flavors like steaming thenthuk with traditional Kangra festive dham feasts.",
  },
  {
    name: "Manali",
    slug: "manali",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Trout fish fry, siddu, babru, and yak cheese",
    seoDescription: "Manali is famous for wood-fired siddu buns, freshwater Himalayan trout, and charming mountain cafes.",
  },
  {
    name: "Mandi",
    slug: "mandi",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Sepu badi, mandyali dham, and kachori",
    seoDescription: "Mandi is celebrated for legendary Sepu badi spinach curry and authentic multi-course ritual Mandyali dham.",
  },
  {
    name: "Solan",
    slug: "solan",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Mushroom soup, siddu, and roasted corn",
    seoDescription: "Solan, the Mushroom City of India, is famous for fresh mushroom preparations and warm hill-station snacks.",
  },
  {
    name: "Kullu",
    slug: "kullu",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "Siddu, red rice, and local fruit wines",
    seoDescription: "Kullu valley is known for stuffed steamed siddu with ghee, indigenous red rice, and crisp Himalayan apples.",
  },
  {
    name: "Baddi",
    slug: "baddi",
    state: "Himachal Pradesh",
    region: "India",
    famousFood: "North Indian thali, parathas, and tea stall snacks",
    seoDescription: "Baddi provides diverse North Indian dining catering to its bustling industrial and commercial community.",
  },
  {
    name: "Jammu",
    slug: "jammu",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Rajma chawal, kaladi kulcha, and sund panjeeri",
    seoDescription: "Jammu is famous for rich Bhaderwah rajma chawal and the irresistible tangy, chewy grilled Kaladi cheese kulcha.",
  },
  {
    name: "Anantnag",
    slug: "anantnag",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Wazwan, rogan josh, and traditional breads",
    seoDescription: "Anantnag is known for fine traditional Kashmiri baking, aromatic saffron kahwa, and festive wazwan banquets.",
  },
  {
    name: "Baramulla",
    slug: "baramulla",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Fish curry, seekh kabab, and noon chai",
    seoDescription: "Baramulla along the Jhelum river is noted for pink salty noon chai with girda bread and local fish dishes.",
  },
  {
    name: "Udhampur",
    slug: "udhampur",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Kaladi, rajma, and chocolate burfi",
    seoDescription: "Udhampur is the home of authentic mountain Kaladi cheese and rich dairy sweets.",
  },
  {
    name: "Kathua",
    slug: "kathua",
    state: "Jammu and Kashmir",
    region: "India",
    famousFood: "Kachalo chaat, puris, and lassi",
    seoDescription: "Kathua offers spicy sweet taro kachalo chaat and comforting roadside Dogra specialties.",
  },
  {
    name: "Jamshedpur",
    slug: "jamshedpur",
    state: "Jharkhand",
    region: "India",
    famousFood: "Litti chokha, mutton curry, rolls, and street chaat",
    seoDescription: "Jamshedpur offers an eclectic food scene with busy roll kiosks, tender mutton curries, and steel city club snacks.",
  },
  {
    name: "Dhanbad",
    slug: "dhanbad",
    state: "Jharkhand",
    region: "India",
    famousFood: "Dhuska, litti chokha, and samosa chaat",
    seoDescription: "Dhanbad is loved for crispy deep-fried dhuska with spicy potato-chana curry and coalfield street foods.",
  },
  {
    name: "Bokaro Steel City",
    slug: "bokaro-steel-city",
    state: "Jharkhand",
    region: "India",
    famousFood: "Litti chokha, dhuska, and Bengali sweets",
    seoDescription: "Bokaro blends authentic Jharkhand tribal snacks with classic Bengali confections.",
  },
  {
    name: "Deoghar",
    slug: "deoghar",
    state: "Jharkhand",
    region: "India",
    famousFood: "Deoghar peda, tilkut, and parathas",
    seoDescription: "Deoghar is renowned for its divine smoky khoya peda sweets offered to pilgrims at Baidyanath temple.",
  },
  {
    name: "Hazaribagh",
    slug: "hazaribagh",
    state: "Jharkhand",
    region: "India",
    famousFood: "Dhuska, chilka roti, and forest mushrooms",
    seoDescription: "Hazaribagh features organic hill-state dishes including rice-flour chilka rotis and seasonal forest produce.",
  },
  {
    name: "Hubballi-Dharwad",
    slug: "hubballi-dharwad",
    state: "Karnataka",
    region: "India",
    famousFood: "Dharwad peda, girmit, mirchi bajji, and jolada rotti",
    seoDescription: "Hubballi-Dharwad is celebrated for iconic brown Dharwad peda sweets and spicy evening girmit puffed rice.",
  },
  {
    name: "Belagavi",
    slug: "belagavi",
    state: "Karnataka",
    region: "India",
    famousFood: "Belgaum kunda, karadantu, and jolada rotti meals",
    seoDescription: "Belagavi is famous for slow-simmered caramelized Kunda milk sweet and wholesome North Karnataka rotti meals.",
  },
  {
    name: "Kalaburagi",
    slug: "kalaburagi",
    state: "Karnataka",
    region: "India",
    famousFood: "Jolada rotti, yennegai, and malkhed peda",
    seoDescription: "Kalaburagi is the capital of North Karnataka cuisine with crisp jowar rotis and spicy stuffed brinjal curry.",
  },
  {
    name: "Davanagere",
    slug: "davanagere",
    state: "Karnataka",
    region: "India",
    famousFood: "Davanagere benne dose, aloo palya, and guladiki laddu",
    seoDescription: "Davanagere is world-famous for crispy, butter-drenched benne dose served with spicy coconut chutney and potato mash.",
  },
  {
    name: "Ballari",
    slug: "ballari",
    state: "Karnataka",
    region: "India",
    famousFood: "Bisi bele bath, cycle khara, and mirchi bajji",
    seoDescription: "Ballari offers zesty evening street snacks, spicy Cycle khara, and rich South Indian rice bowls.",
  },
  {
    name: "Vijayapura",
    slug: "vijayapura",
    state: "Karnataka",
    region: "India",
    famousFood: "Jolada rotti, shenga chutney, and biryani",
    seoDescription: "Vijayapura pairs historical Deccan culinary heritage with wholesome millet rotis and peanut powder.",
  },
  {
    name: "Shivamogga",
    slug: "shivamogga",
    state: "Karnataka",
    region: "India",
    famousFood: "Halasina hannina kadabu, akki rotti, and filter coffee",
    seoDescription: "Shivamogga in the Malnad gateway features fragrant jackfruit steamed dumplings and crispy rice-flour akki rotti.",
  },
  {
    name: "Tumakuru",
    slug: "tumakuru",
    state: "Karnataka",
    region: "India",
    famousFood: "Thatte idli, coconut sweets, and benne murukku",
    seoDescription: "Tumakuru is famous for super-soft plate-sized thatte idlis served with spicy red chutney and dollops of butter.",
  },
  {
    name: "Udupi",
    slug: "udupi",
    state: "Karnataka",
    region: "India",
    famousFood: "Udupi sambar, masala dosa, goli baje, and neer dosa",
    seoDescription: "Udupi is the legendary birthplace of iconic South Indian vegetarian restaurant cuisine, soft neer dosa, and crisp goli baje.",
  },
  {
    name: "Kollam",
    slug: "kollam",
    state: "Kerala",
    region: "India",
    famousFood: "Kollam cashew dishes, tapioca with fish curry, and appam",
    seoDescription: "Kollam is the cashew capital of India, renowned for lake fish curries, spicy kappa, and soft appam.",
  },
  {
    name: "Palakkad",
    slug: "palakkad",
    state: "Kerala",
    region: "India",
    famousFood: "Ramaswamy idli, palakkadan matta rice, and avail",
    seoDescription: "Palakkad features unique Kerala-Tamil fusion cuisine with wholesome red matta rice and coconut-rich avial.",
  },
  {
    name: "Alappuzha",
    slug: "alappuzha",
    state: "Kerala",
    region: "India",
    famousFood: "Karimeen pollichathu, prawn roast, and duck mappas",
    seoDescription: "Alappuzha is famous for backwater pearl spot (karimeen) baked in banana leaves and coconut-infused duck curries.",
  },
  {
    name: "Kannur",
    slug: "kannur",
    state: "Kerala",
    region: "India",
    famousFood: "Thalassery biryani, unnakkayi, and kallummakkaya fry",
    seoDescription: "Kannur and the Malabar coast are acclaimed for fragrant short-grain biryani and sweet plantain unnakkayi snacks.",
  },
  {
    name: "Kottayam",
    slug: "kottayam",
    state: "Kerala",
    region: "India",
    famousFood: "Kottayam fish curry, beef fry with parotta, and duck roast",
    seoDescription: "Kottayam is famed for fiery red fish curries with kodampuli and flaky Malabar parotta with roasted meats.",
  },
  {
    name: "Malappuram",
    slug: "malappuram",
    state: "Kerala",
    region: "India",
    famousFood: "Neypathiri, chicken chukka, and sulaimani tea",
    seoDescription: "Malappuram offers delicate rice pancakes, richly spiced Malabar curries, and digestive spiced sulaimani tea.",
  },
  {
    name: "Leh",
    slug: "leh",
    state: "Ladakh",
    region: "India",
    famousFood: "Skyu, thukpa, tingmo, momos, and apricot jam",
    seoDescription: "Leh offers hearty high-altitude Ladakhi cooking including root vegetable skyu pasta, steamed tingmo bread, and wild apricot treats.",
  },
  {
    name: "Kargil",
    slug: "kargil",
    state: "Ladakh",
    region: "India",
    famousFood: "Mamtu dumplings, barley soup, and salted tea",
    seoDescription: "Kargil features wholesome roasted barley tsampa, delicate mutton dumplings, and warming mountain broths.",
  },
  {
    name: "Kavaratti",
    slug: "kavaratti",
    state: "Lakshadweep",
    region: "India",
    famousFood: "Tuna fish curry, coconut rice, and rayereha",
    seoDescription: "Kavaratti showcases fresh skipjack tuna cooked in creamy coconut milk and traditional island island spices.",
  },
  {
    name: "Agatti",
    slug: "agatti",
    state: "Lakshadweep",
    region: "India",
    famousFood: "Barbecued fish, coconut sweets, and sea crab",
    seoDescription: "Agatti island offers freshly caught grilled lagoon fish and traditional sweet coconut bondas.",
  },
  {
    name: "Andrott",
    slug: "andrott",
    state: "Lakshadweep",
    region: "India",
    famousFood: "Smoked tuna, pathiri, and island halwa",
    seoDescription: "Andrott features historic island delicacies with thin rice pathiris and long-preserved smoked masmin tuna.",
  },
  {
    name: "Minicoy",
    slug: "minicoy",
    state: "Lakshadweep",
    region: "India",
    famousFood: "Farhi, holhi, and tuna biryani",
    seoDescription: "Minicoy has a distinctive Mahl food culture with tuna-stuffed snacks and aromatic coconut rice.",
  },
  {
    name: "Jabalpur",
    slug: "jabalpur",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Khoya jalebi, bhedavari, and chaat",
    seoDescription: "Jabalpur is renowned for thick, dark khoya jalebis, crispy urad dal bhedavi puris, and vibrant street snacks.",
  },
  {
    name: "Ujjain",
    slug: "ujjain",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Poha jalebi, sabudana khichdi, and Malwa thali",
    seoDescription: "Ujjain offers divine temple town street foods including fluffy spiced poha, crispy jalebi, and light sabudana khichdi.",
  },
  {
    name: "Sagar",
    slug: "sagar",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Chironji barfi, samosa, and namkeen",
    seoDescription: "Sagar in Bundelkhand is famous for rare chironji seed barfi and crispy spicy namkeens.",
  },
  {
    name: "Dewas",
    slug: "dewas",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Sev, poha, and rabdi",
    seoDescription: "Dewas shares Malwa's love for crunchy sev varieties, morning poha breakfasts, and chilled rabdi.",
  },
  {
    name: "Satna",
    slug: "satna",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Mawa bati, kachori, and samosa",
    seoDescription: "Satna offers rich Bundelkhandi sweets like mawa bati alongside street-corner fried kachoris.",
  },
  {
    name: "Ratlam",
    slug: "ratlam",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Ratlami sev, dal bafla, and hing kachori",
    seoDescription: "Ratlam is internationally famous for spicy, clove-infused Ratlami sev and golden ghee-drizzled dal bafla.",
  },
  {
    name: "Rewa",
    slug: "rewa",
    state: "Madhya Pradesh",
    region: "India",
    famousFood: "Bagheli thali, dehati rasgulla, and samosa",
    seoDescription: "Rewa presents hearty Baghelkhand flavors with rustic seasonal gravies and traditional syrup-soaked sweets.",
  },
  {
    name: "Thane",
    slug: "thane",
    state: "Maharashtra",
    region: "India",
    famousFood: "Misal pav, vada pav, coastal seafood, and modak",
    seoDescription: "Thane is famous for fiery misal pav joints, coastal Konkani seafood diners, and festive sweet ukdiche modak.",
  },
  {
    name: "Navi Mumbai",
    slug: "navi-mumbai",
    state: "Maharashtra",
    region: "India",
    famousFood: "Pav bhaji, koli fish fry, and Frankie rolls",
    seoDescription: "Navi Mumbai boasts coastal Agri-Koli seafood specialists and bustling street food boulevards.",
  },
  {
    name: "Pimpri-Chinchwad",
    slug: "pimpri-chinchwad",
    state: "Maharashtra",
    region: "India",
    famousFood: "Vada pav, bhakarwadi, and misal",
    seoDescription: "Pimpri-Chinchwad features iconic industrial-hub breakfast stalls, piping hot vada pavs, and crunchy snacks.",
  },
  {
    name: "Kalyan-Dombivli",
    slug: "kalyan-dombivli",
    state: "Maharashtra",
    region: "India",
    famousFood: "Misal pav, dabeli, and shev pav",
    seoDescription: "Kalyan-Dombivli is known for fast-paced station road snacks, spicy dabeli, and local misal recipes.",
  },
  {
    name: "Vasai-Virar",
    slug: "vasai-virar",
    state: "Maharashtra",
    region: "India",
    famousFood: "Kupari pork vindaloo, pan-fried fish, and poha",
    seoDescription: "Vasai-Virar showcases unique East Indian Kupari culinary heritage with coastal seafood and fragrant bottle masala.",
  },
  {
    name: "Chhatrapati Sambhajinagar",
    slug: "chhatrapati-sambhajinagar",
    state: "Maharashtra",
    region: "India",
    famousFood: "Naan qalia, tahri, and imarti",
    seoDescription: "Chhatrapati Sambhajinagar is famous for royal aromatic Naan Qalia and crisp, syrup-filled imartis.",
  },
  {
    name: "Solapur",
    slug: "solapur",
    state: "Maharashtra",
    region: "India",
    famousFood: "Shenga chutney, jowar bhakri, and Solapuri mutton",
    seoDescription: "Solapur is famous for zesty roasted peanut shenga chutney and fiery red mutton gravies with jowar flatbread.",
  },
  {
    name: "Amravati",
    slug: "amravati",
    state: "Maharashtra",
    region: "India",
    famousFood: "Gulgule, sambar vadi, and spicy tarri poha",
    seoDescription: "Amravati offers Vidarbha comfort foods including coriander-stuffed sambar vadis and spicy tarri poha.",
  },
  {
    name: "Kolhapur",
    slug: "kolhapur",
    state: "Maharashtra",
    region: "India",
    famousFood: "Kolhapuri misal, tambra rassa, pandhra rassa, and jaggery",
    seoDescription: "Kolhapur is legendary for fiery tambra rassa red curry, soothing white pandhra rassa, and spicy Kolhapuri misal.",
  },
  {
    name: "Nanded",
    slug: "nanded",
    state: "Maharashtra",
    region: "India",
    famousFood: "Langar prasad, biryani, and tehri",
    seoDescription: "Nanded is known for pilgrim langar hospitality, hearty Marathwada lentils, and aromatic rice dishes.",
  },
  {
    name: "Sangli",
    slug: "sangli",
    state: "Maharashtra",
    region: "India",
    famousFood: "Bhadang, jowar bhakri, and turmeric specials",
    seoDescription: "Sangli, the Turmeric City of Maharashtra, is famous for crunchy spiced Kolhapuri-Sangli bhadang puffed rice.",
  },
  {
    name: "Jalgaon",
    slug: "jalgaon",
    state: "Maharashtra",
    region: "India",
    famousFood: "Shev bhaji, bharit, and banana chips",
    seoDescription: "Jalgaon is world-renowned for spicy roadside shev bhaji and smoky eggplant Khandeshi bharit with puris.",
  },
  {
    name: "Imphal",
    slug: "imphal",
    state: "Manipur",
    region: "India",
    famousFood: "Kangshoi, singju, eromba, and chak-hao kheer",
    seoDescription: "Imphal is celebrated for fresh vegetable stews (kangshoi), spicy fermented fish eromba, and purple black rice kheer.",
  },
  {
    name: "Churachandpur",
    slug: "churachandpur",
    state: "Manipur",
    region: "India",
    famousFood: "Smoked beef, bamboo shoot stew, and sticky rice",
    seoDescription: "Churachandpur highlights indigenous tribal culinary traditions with slow-smoked meats and garden-fresh herbs.",
  },
  {
    name: "Thoubal",
    slug: "thoubal",
    state: "Manipur",
    region: "India",
    famousFood: "Fish curry, ngari chutney, and wild greens",
    seoDescription: "Thoubal on the river valley offers organic freshwater fish specialties and aromatic herb salads.",
  },
  {
    name: "Bishnupur",
    slug: "bishnupur",
    state: "Manipur",
    region: "India",
    famousFood: "Loktak lake fish, singju, and lotus stem curry",
    seoDescription: "Bishnupur, home of Loktak Lake, is famous for lake fish delicacies and crispy spicy raw vegetable singju salad.",
  },
  {
    name: "Shillong",
    slug: "shillong",
    state: "Meghalaya",
    region: "India",
    famousFood: "Jadoh, dohkleh, tungrymbai, and momos",
    seoDescription: "Shillong is renowned for Khasi culinary masterworks like meat-cooked jadoh rice, pork salads, and vibrant cafe menus.",
  },
  {
    name: "Tura",
    slug: "tura",
    state: "Meghalaya",
    region: "India",
    famousFood: "Wak gominda, nakham bitchi, and kappa",
    seoDescription: "Tura in the Garo Hills is celebrated for pumpkin pork stews (wak gominda) and dry fish broth.",
  },
  {
    name: "Jowai",
    slug: "jowai",
    state: "Meghalaya",
    region: "India",
    famousFood: "Jaintia meat curry, smoked fish, and rice beer",
    seoDescription: "Jowai features authentic Pnar culinary traditions with sesame-infused gravies and mountain herbs.",
  },
  {
    name: "Cherrapunji",
    slug: "cherrapunji",
    state: "Meghalaya",
    region: "India",
    famousFood: "Sohra honey, jadoh, and mountain pork",
    seoDescription: "Cherrapunji (Sohra) offers warming rain-swept comfort foods, wild wildflower honey, and hearty rice platters.",
  },
  {
    name: "Aizawl",
    slug: "aizawl",
    state: "Mizoram",
    region: "India",
    famousFood: "Bai, vawksa rep, sawhchiar, and bamboo shoots",
    seoDescription: "Aizawl is celebrated for soothing vegetable bai stew with pork, smoked vawksa rep, and festive sawhchiar rice porridge.",
  },
  {
    name: "Lunglei",
    slug: "lunglei",
    state: "Mizoram",
    region: "India",
    famousFood: "Smoked meat stew, boiled greens, and sticky rice",
    seoDescription: "Lunglei offers authentic southern Mizo home-style cooking with pure, unspiced natural flavors.",
  },
  {
    name: "Champhai",
    slug: "champhai",
    state: "Mizoram",
    region: "India",
    famousFood: "Grape wine, local fish curry, and bamboo shoot fry",
    seoDescription: "Champhai, the rice bowl of Mizoram, is famous for vineyard wines and fragrant organic rice varieties.",
  },
  {
    name: "Kohima",
    slug: "kohima",
    state: "Nagaland",
    region: "India",
    famousFood: "Smoked pork with axone, raja mircha chutney, and galho",
    seoDescription: "Kohima is famous for legendary fermented soybean (axone) curries, fiery Naga ghost pepper chutneys, and soothing galho.",
  },
  {
    name: "Dimapur",
    slug: "dimapur",
    state: "Nagaland",
    region: "India",
    famousFood: "Pork with bamboo shoots, roasted beef, and momos",
    seoDescription: "Dimapur offers bustling night market stalls with flame-grilled meats, bamboo shoot delicacies, and steaming dumplings.",
  },
  {
    name: "Mokokchung",
    slug: "mokokchung",
    state: "Nagaland",
    region: "India",
    famousFood: "Ao pork curry, dried fish stew, and yam leaves",
    seoDescription: "Mokokchung is the heart of Ao Naga culinary culture, known for delicate smoked meats and wood-fire cooked greens.",
  },
  {
    name: "Cuttack",
    slug: "cuttack",
    state: "Odisha",
    region: "India",
    famousFood: "Dahi bara aloo dum, thunka puri, and chhena gaja",
    seoDescription: "Cuttack is legendary across Odisha for refreshing Dahi bara aloo dum with spicy ghugni and crispy thunka puris.",
  },
  {
    name: "Rourkela",
    slug: "rourkela",
    state: "Odisha",
    region: "India",
    famousFood: "Chhena poda, aloo chop, and rasagola",
    seoDescription: "Rourkela brings together tribal Odia foods, caramel-crusted chhena poda, and spicy street chops.",
  },
  {
    name: "Berhampur",
    slug: "berhampur",
    state: "Odisha",
    region: "India",
    famousFood: "Berhampuri papad, achar, and puri upma",
    seoDescription: "Berhampur (Brahmapur) is renowned for savory spiced papads, pungent pickles, and breakfast puri upma.",
  },
  {
    name: "Sambalpur",
    slug: "sambalpur",
    state: "Odisha",
    region: "India",
    famousFood: "Sarsatia sweet, pakhala, and chaul bara",
    seoDescription: "Sambalpur is famous for rare ganjer bark sarsatia sweets and crispy deep-fried rice chaul baras.",
  },
  {
    name: "Puri",
    slug: "puri",
    state: "Odisha",
    region: "India",
    famousFood: "Chhappan bhog, khaja, malpua, and dalma",
    seoDescription: "Puri is the holy seat of Lord Jagannath's revered Mahaprasad, flaky sweet khaja, and seaside fish fries.",
  },
  {
    name: "Balasore",
    slug: "balasore",
    state: "Odisha",
    region: "India",
    famousFood: "Mudhi mansa, fresh seafood, and rasagola",
    seoDescription: "Balasore is famous for the mouthwatering combination of crunchy puffed rice with spicy mutton curry (mudhi mansa).",
  },
  {
    name: "Puducherry",
    slug: "puducherry",
    state: "Puducherry",
    region: "India",
    famousFood: "Croissants, baguettes, crepes, and Franco-Tamil seafood",
    seoDescription: "Puducherry blends French colonial cafe culture with coastal Tamil spice in fragrant seafood bouillabaisse and freshly baked breads.",
  },
  {
    name: "Karaikal",
    slug: "karaikal",
    state: "Puducherry",
    region: "India",
    famousFood: "Crab masala, squid fry, and coastal fish curry",
    seoDescription: "Karaikal offers rich port-town coastal dining with deep-sea crabs, squid, and savory parottas.",
  },
  {
    name: "Mahe",
    slug: "mahe",
    state: "Puducherry",
    region: "India",
    famousFood: "Malabar biryani, kallummakkaya, and halwa",
    seoDescription: "Mahe enclave on the Arabian coast shares Kerala's rich Malabar spice routes and seaside snacks.",
  },
  {
    name: "Yanam",
    slug: "yanam",
    state: "Puducherry",
    region: "India",
    famousFood: "Godavari fish pulusu, prawn fry, and pootharekulu",
    seoDescription: "Yanam on the Godavari delta is famous for fiery Andhra-style fish curries and freshwater prawns.",
  },
  {
    name: "Patiala",
    slug: "patiala",
    state: "Punjab",
    region: "India",
    famousFood: "Patiala shahi chicken, makki di roti, sarson da saag, and lassi",
    seoDescription: "Patiala is world-famous for royal Punjabi hospitality, hearty sarson da saag with golden makki rotis, and giant sweet lassis.",
  },
  {
    name: "Bathinda",
    slug: "bathinda",
    state: "Punjab",
    region: "India",
    famousFood: "Dal makhani, kheer, parathas, and winter saag",
    seoDescription: "Bathinda in the Malwa heartland serves rich farm-fresh dairy, slow-simmered dal makhani, and tandoori parathas.",
  },
  {
    name: "Mohali",
    slug: "mohali",
    state: "Punjab",
    region: "India",
    famousFood: "Butter chicken, tandoori soya chaap, rolls, and cold coffee",
    seoDescription: "Mohali boasts vibrant Tri-city dining with modern sports bars, highway dhaba favorites, and street food stalls.",
  },
  {
    name: "Pathankot",
    slug: "pathankot",
    state: "Punjab",
    region: "India",
    famousFood: "Chhole bhature, dal makhani, and highway parathas",
    seoDescription: "Pathankot at the foothills offers famous highway dhaba breakfast stops with fluffy bhaturas and steaming tea.",
  },
  {
    name: "Hoshiarpur",
    slug: "hoshiarpur",
    state: "Punjab",
    region: "India",
    famousFood: "Peda, lassi, kachori, and Punjabi thali",
    seoDescription: "Hoshiarpur is known for rich traditional dairy sweets, thick lassi, and comforting Doaba vegetarian fare.",
  },
  {
    name: "Batala",
    slug: "batala",
    state: "Punjab",
    region: "India",
    famousFood: "Amritsari kulcha, puri chana, and pinni",
    seoDescription: "Batala features historic gurdwaras, crisp clay-oven baked stuffed kulchas, and winter urad dal pinnis.",
  },
  {
    name: "Moga",
    slug: "moga",
    state: "Punjab",
    region: "India",
    famousFood: "Desi ghee jalebi, kachori, and sarson da saag",
    seoDescription: "Moga in Malwa is loved for deep-fried golden jalebis and authentic country-style winter meals.",
  },
  {
    name: "Abohar",
    slug: "abohar",
    state: "Punjab",
    region: "India",
    famousFood: "Kinnow juice, sweets, and dal baati churma",
    seoDescription: "Abohar, the Kinnow Capital, blends Punjabi and Rajasthani border flavors with fresh citrus and hearty meals.",
  },
  {
    name: "Khanna",
    slug: "khanna",
    state: "Punjab",
    region: "India",
    famousFood: "Tandoori chicken, butter naan, and sweet lassi",
    seoDescription: "Khanna, Asia's largest grain market, features robust highway dining with buttery curries and crisp naans.",
  },
  {
    name: "Phagwara",
    slug: "phagwara",
    state: "Punjab",
    region: "India",
    famousFood: "Chaat, paneer tikka, samosa, and kulfi",
    seoDescription: "Phagwara on GT Road is celebrated for bustling evening street food markets and rich dairy desserts.",
  },
  {
    name: "Kapurthala",
    slug: "kapurthala",
    state: "Punjab",
    region: "India",
    famousFood: "Shahi paneer, parathas, and gulab jamun",
    seoDescription: "Kapurthala, the Paris of Punjab, pairs royal heritage architecture with delicate North Indian curries.",
  },
  {
    name: "Firozpur",
    slug: "firozpur",
    state: "Punjab",
    region: "India",
    famousFood: "Makki roti, sarson saag, and border dhaba meals",
    seoDescription: "Firozpur on the historic frontier serves hearty Punjabi rustic meals with fresh churned butter.",
  },
  {
    name: "Kota",
    slug: "kota",
    state: "Rajasthan",
    region: "India",
    famousFood: "Kota kachori, dal baati churma, and ghevar",
    seoDescription: "Kota is famous for its spicy urad dal and hing stuffed Kota kachoris with tangy coriander chutneys.",
  },
  {
    name: "Bikaner",
    slug: "bikaner",
    state: "Rajasthan",
    region: "India",
    famousFood: "Bikaneri bhujia, rasgulla, ghevar, and raj kachori",
    seoDescription: "Bikaner is the world capital of crispy moth dal bhujia namkeen and mouth-melting syrupy white rasgullas.",
  },
  {
    name: "Ajmer",
    slug: "ajmer",
    state: "Rajasthan",
    region: "India",
    famousFood: "Sohan halwa, kadi kachori, and biryani",
    seoDescription: "Ajmer is renowned for nutty circular Sohan halwa confections and breakfast kachoris drenched in sour kadhi.",
  },
  {
    name: "Bhilwara",
    slug: "bhilwara",
    state: "Rajasthan",
    region: "India",
    famousFood: "Makki ka ghat, gatte ki sabzi, and rabdi",
    seoDescription: "Bhilwara in Mewar is known for hearty corn dishes, spiced gram flour dumplings, and sweet condensed milk.",
  },
  {
    name: "Alwar",
    slug: "alwar",
    state: "Rajasthan",
    region: "India",
    famousFood: "Alwar ka kalakand (milk cake), kachori, and parathas",
    seoDescription: "Alwar is internationally famous for caramelized crumbly Alwar milk cake and spicy roadside snacks.",
  },
  {
    name: "Sikar",
    slug: "sikar",
    state: "Rajasthan",
    region: "India",
    famousFood: "Peda, pyaaz kachori, and bajra rotla",
    seoDescription: "Sikar in Shekhawati offers wholesome desert millet meals, crunchy onion kachoris, and fresh dairy sweets.",
  },
  {
    name: "Bharatpur",
    slug: "bharatpur",
    state: "Rajasthan",
    region: "India",
    famousFood: "Bedai, jalebi, kachori, and mustard greens",
    seoDescription: "Bharatpur borders the Braj region, offering morning bedai puris with spicy potato curry and hot jalebis.",
  },
  {
    name: "Sri Ganganagar",
    slug: "sri-ganganagar",
    state: "Rajasthan",
    region: "India",
    famousFood: "Kinnow juice, Punjabi parathas, and dal baati",
    seoDescription: "Sri Ganganagar on the canal plains blends Rajasthani dal baati with Punjab-influenced dairy and citrus.",
  },
  {
    name: "Gangtok",
    slug: "gangtok",
    state: "Sikkim",
    region: "India",
    famousFood: "Momos, thukpa, kinema curry, phagshapa, and chhurpi",
    seoDescription: "Gangtok offers authentic Himalayan delicacies including pork phagshapa, hard chhurpi cheese, and street momos.",
  },
  {
    name: "Namchi",
    slug: "namchi",
    state: "Sikkim",
    region: "India",
    famousFood: "Sael roti, momos, and fermented bamboo shoot soup",
    seoDescription: "Namchi in South Sikkim is known for crispy sweet rice sael roti and organic mountain dining.",
  },
  {
    name: "Geyzing",
    slug: "geyzing",
    state: "Sikkim",
    region: "India",
    famousFood: "Gundruk soup, momos, and tongba millet beer",
    seoDescription: "Geyzing (Gyalshing) features warming fermented leaf gundruk soups and warm bamboo-pot tongba.",
  },
  {
    name: "Rangpo",
    slug: "rangpo",
    state: "Sikkim",
    region: "India",
    famousFood: "Steamed momos, thukpa, and highway tea snacks",
    seoDescription: "Rangpo on the Teesta river border is the gateway to Sikkim, famous for welcoming roadside dumpling stalls.",
  },
  {
    name: "Tiruppur",
    slug: "tiruppur",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Kongunadu chicken, pallipalayam chicken, and parotta",
    seoDescription: "Tiruppur in the Kongu belt is celebrated for tender coconut-shallot Pallipalayam chicken and parottas.",
  },
  {
    name: "Erode",
    slug: "erode",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Kothu parotta, nattu kozhi soup, and turmeric rice",
    seoDescription: "Erode is famous for aromatic country chicken broths, lively street kothu parotta, and turmeric dishes.",
  },
  {
    name: "Tirunelveli",
    slug: "tirunelveli",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Tirunelveli halwa, sodhi, and parotta",
    seoDescription: "Tirunelveli is world-renowned for silky, glistening wheat Tirunelveli halwa served piping hot.",
  },
  {
    name: "Vellore",
    slug: "vellore",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Vellore biryani, makkan peda, and filter coffee",
    seoDescription: "Vellore is famous for rich Arcot-style biryani and the decadent, syrup-drenched Makkan peda sweet.",
  },
  {
    name: "Thoothukudi",
    slug: "thoothukudi",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Tuticorin macaroon, sea fish curry, and parotta",
    seoDescription: "Thoothukudi is acclaimed for airy cashew-egg white macaroons and fiery coastal seafood curries.",
  },
  {
    name: "Dindigul",
    slug: "dindigul",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Dindigul thalappakatti biryani, parotta, and halwa",
    seoDescription: "Dindigul is globally celebrated for fragrant seeraga samba Thalappakatti biryani cooked with tender meats.",
  },
  {
    name: "Thanjavur",
    slug: "thanjavur",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Ashoka halwa, thavala vadai, and Cauvery meals",
    seoDescription: "Thanjavur, the rice bowl of Tamil Nadu, is famous for moong dal Ashoka halwa and temple culinary traditions.",
  },
  {
    name: "Hosur",
    slug: "hosur",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Dosa, filter coffee, biryani, and multi-cuisine",
    seoDescription: "Hosur on the Karnataka border offers a delicious blend of Tamil comfort breakfasts and Bengaluru-style cafe bites.",
  },
  {
    name: "Kanchipuram",
    slug: "kanchipuram",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Kanchipuram idli, kovil vadai, and filter coffee",
    seoDescription: "Kanchipuram is world-famous for cylindrical Kanchipuram idlis spiced with pepper, cumin, ginger, and ghee.",
  },
  {
    name: "Nagercoil",
    slug: "nagercoil",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Nanjil nandu masala, banana chips, and appam",
    seoDescription: "Nagercoil features Nanjil Nadu cuisine blending rich coconut gravies, spicy crab roasts, and crispy banana chips.",
  },
  {
    name: "Ooty",
    slug: "ooty",
    state: "Tamil Nadu",
    region: "India",
    famousFood: "Homemade chocolates, Ooty varkey, and Nilgiri tea",
    seoDescription: "Ooty is famous for crunchy layered baker's varkey, artisanal chocolates, and freshly brewed Nilgiri black tea.",
  },
  {
    name: "Warangal",
    slug: "warangal",
    state: "Telangana",
    region: "India",
    famousFood: "Sarva pindi, potlakaya pulusu, and bagara rice",
    seoDescription: "Warangal is celebrated for savory crisp rice-flour sarva pindi pancakes and aromatic bagara rice.",
  },
  {
    name: "Nizamabad",
    slug: "nizamabad",
    state: "Telangana",
    region: "India",
    famousFood: "Jowar roti, mutton dalcha, and bagara khana",
    seoDescription: "Nizamabad offers robust northern Telangana cuisine with jowar flatbreads and slow-cooked dalcha.",
  },
  {
    name: "Khammam",
    slug: "khammam",
    state: "Telangana",
    region: "India",
    famousFood: "Khammam idli, spicy mirchi bajji, and gongura mutton",
    seoDescription: "Khammam is loved for soft morning idlis, tangy gongura curries, and evening street fritters.",
  },
  {
    name: "Karimnagar",
    slug: "karimnagar",
    state: "Telangana",
    region: "India",
    famousFood: "Kudumulu, sakinalu, and natukodi pulusu",
    seoDescription: "Karimnagar is renowned for crunchy sesame festival sakinalu spirals and country chicken curries.",
  },
  {
    name: "Ramagundam",
    slug: "ramagundam",
    state: "Telangana",
    region: "India",
    famousFood: "Biryani, bagara rice, and chicken fry",
    seoDescription: "Ramagundam features spicy Godavari basin non-vegetarian curries and fragrant seasoned rice.",
  },
  {
    name: "Mahbubnagar",
    slug: "mahbubnagar",
    state: "Telangana",
    region: "India",
    famousFood: "Ragi sankati, boti curry, and jowar roti",
    seoDescription: "Mahbubnagar in Palamuru is famous for wholesome ragi millet balls and robust rural gravies.",
  },
  {
    name: "Nalgonda",
    slug: "nalgonda",
    state: "Telangana",
    region: "India",
    famousFood: "Pacchi pulusu, sarva pindi, and pesarattu",
    seoDescription: "Nalgonda features refreshing unboiled tamarind pacchi pulusu and crispy skillet sarva pindi.",
  },
  {
    name: "Agartala",
    slug: "agartala",
    state: "Tripura",
    region: "India",
    famousFood: "Mui borok, berma chutney, chakhwi, and sweets",
    seoDescription: "Agartala is famous for indigenous Tripuri dishes prepared with fermented berma fish, bamboo shoots, and fresh herbs.",
  },
  {
    name: "Dharmanagar",
    slug: "dharmanagar",
    state: "Tripura",
    region: "India",
    famousFood: "Fish curry, momos, and Bengali sweets",
    seoDescription: "Dharmanagar in northern Tripura offers delicious riverine fish curries and traditional Bengali dairy sweets.",
  },
  {
    name: "Udaipur",
    slug: "udaipur-tripura",
    state: "Tripura",
    region: "India",
    famousFood: "Peda, temple prasad, and fish fry",
    seoDescription: "Udaipur, the Lake City of Tripura, is famous for holy Tripureswari temple pedas and freshwater delicacies.",
  },
  {
    name: "Kailashahar",
    slug: "kailashahar",
    state: "Tripura",
    region: "India",
    famousFood: "Chakhwi, fried fish, and bamboo shoots",
    seoDescription: "Kailashahar near Unakoti offers authentic tribal stews and fragrant regional home-style meals.",
  },
  {
    name: "Ghaziabad",
    slug: "ghaziabad",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Chaat, tandoori soya chaap, parathas, and sweets",
    seoDescription: "Ghaziabad is known for bustling NCR street food hubs, tandoori snacks, and rich North Indian curries.",
  },
  {
    name: "Meerut",
    slug: "meerut",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Nan khatai, revdi, gajak, and seekh kabab",
    seoDescription: "Meerut is historic for oven-baked melt-in-mouth Nan khatai biscuits, winter rewari, and succulent tandoori kababs.",
  },
  {
    name: "Prayagraj",
    slug: "prayagraj",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Allahabadi gujiya, dam aloo, chaat, and kachori",
    seoDescription: "Prayagraj is famous for Sangam morning kachori-sabzi, spicy dam aloo, and festive mawa gujiyas.",
  },
  {
    name: "Bareilly",
    slug: "bareilly",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Seekh kebabs, kachori, and jalebi",
    seoDescription: "Bareilly is celebrated for authentic Rohilkhand flavors including smoky seekh kebabs and morning sweet jalebis.",
  },
  {
    name: "Aligarh",
    slug: "aligarh",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Barula chaat, seekh kebab, and halwa",
    seoDescription: "Aligarh is legendary for crispy boiled baby potato barulas fried and coated in fiery green chili chutney.",
  },
  {
    name: "Moradabad",
    slug: "moradabad",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Moradabadi dal, moong dal chaat, and jalebi",
    seoDescription: "Moradabad is world-famous for delicate Moradabadi moong dal garnished with butter, cumin, and dried red chilies.",
  },
  {
    name: "Saharanpur",
    slug: "saharanpur",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Mangoes, chaat, and bedmi puri",
    seoDescription: "Saharanpur offers luscious orchard mango varieties, crispy morning bedmi puris, and bazaar sweets.",
  },
  {
    name: "Gorakhpur",
    slug: "gorakhpur",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Galawati kabab, litti chokha, and rabdi",
    seoDescription: "Gorakhpur blends Awadhi royal kebabs with eastern UP rustic litti chokha and creamy condensed rabdi.",
  },
  {
    name: "Firozabad",
    slug: "firozabad",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Chaat, bedai, and sweet petha",
    seoDescription: "Firozabad, the Glass City, features lively Braj street snacks, morning bedai-aloo, and syrupy pethas.",
  },
  {
    name: "Jhansi",
    slug: "jhansi",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Bundeli thali, kachori, and ras kheer",
    seoDescription: "Jhansi is known for historic Bundelkhandi delicacies with spicy fried kachoris and sweet winter ras kheer.",
  },
  {
    name: "Muzaffarnagar",
    slug: "muzaffarnagar",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Jaggery (gur), chaat, and dal makhani",
    seoDescription: "Muzaffarnagar, the Jaggery Capital of India, is famous for fresh organic gur varieties and sugarcane treats.",
  },
  {
    name: "Mathura",
    slug: "mathura",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Mathura ke peda, kachori jalebi, and makhan mishri",
    seoDescription: "Mathura is globally famous for divine browned mawa pedas and crispy morning kachoris with tangy potato curry.",
  },
  {
    name: "Ayodhya",
    slug: "ayodhya",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Laddoo, rabdi, samosa, and bedmi puri",
    seoDescription: "Ayodhya offers divine temple sweets, gram flour besan laddoos, and traditional Awadhi vegetarian feasts.",
  },
  {
    name: "Greater Noida",
    slug: "greater-noida",
    state: "Uttar Pradesh",
    region: "India",
    famousFood: "Street momos, rolls, cafe food, and North Indian meals",
    seoDescription: "Greater Noida offers modern educational and tech hub dining with multi-cuisine options and student cafes.",
  },
  {
    name: "Haridwar",
    slug: "haridwar",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Kachori with aloo sabzi, jalebi, rabdi, and peda",
    seoDescription: "Haridwar is famous along the Ganges for piping hot breakfast kachoris, giant jalebis, and divine milk sweets.",
  },
  {
    name: "Roorkee",
    slug: "roorkee",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Parathas, chaat, and North Indian meals",
    seoDescription: "Roorkee combines student-town street snacks with rich North Indian dhaba classics.",
  },
  {
    name: "Haldwani",
    slug: "haldwani",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Bal mithai, singori, bhatt ki churkani, and momos",
    seoDescription: "Haldwani is the gateway to Kumaon, celebrated for chocolate-like bal mithai and nutritious black soy bhatt curries.",
  },
  {
    name: "Rudrapur",
    slug: "rudrapur",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Kumaoni thali, samosa, and lassi",
    seoDescription: "Rudrapur in the Terai region offers a blend of Kumaon mountain delicacies and rich agricultural plains cuisine.",
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Ayurvedic satvik meals, cafe wood-fired pizza, and chai",
    seoDescription: "Rishikesh, the Yoga Capital, is renowned for wholesome organic satvik dining and scenic Ganges riverside cafes.",
  },
  {
    name: "Nainital",
    slug: "nainital",
    state: "Uttarakhand",
    region: "India",
    famousFood: "Aloo ke gutke, bal mithai, momos, and hot chocolate",
    seoDescription: "Nainital features spicy roasted mountain potatoes (aloo ke gutke), Mall Road steaming momos, and lakeside bakeries.",
  },
  {
    name: "Howrah",
    slug: "howrah",
    state: "West Bengal",
    region: "India",
    famousFood: "Kachori sabzi, telebhaja, rolls, and mishti",
    seoDescription: "Howrah is famous for busy station morning kachoris, crispy evening vegetable telebhaja fritters, and sweet shops.",
  },
  {
    name: "Asansol",
    slug: "asansol",
    state: "West Bengal",
    region: "India",
    famousFood: "Litti chokha, mutton curry, kathi rolls, and rasgulla",
    seoDescription: "Asansol blends Bengal and Jharkhand culinary traditions with spicy meat curries and syrup-soaked sweets.",
  },
  {
    name: "Durgapur",
    slug: "durgapur",
    state: "West Bengal",
    region: "India",
    famousFood: "Fish fry, singara, mishti doi, and egg rolls",
    seoDescription: "Durgapur is celebrated for golden Kolkata-style fish cutlets, evening singara samosas, and creamy earthen pot mishti doi.",
  },
  {
    name: "Bardhaman",
    slug: "bardhaman",
    state: "West Bengal",
    region: "India",
    famousFood: "Mihidana, sitabhog, and Bengali fish meals",
    seoDescription: "Bardhaman (Burdwan) is internationally famous for royal sweet masterworks: golden Mihidana and delicate Sitabhog.",
  },
  {
    name: "Malda",
    slug: "malda",
    state: "West Bengal",
    region: "India",
    famousFood: "Fazli mangoes, rasakadamba sweets, and fish curry",
    seoDescription: "Malda is globally renowned for giant Fazli mangoes and the unique textured rasakadamba sweet.",
  },
  {
    name: "Kharagpur",
    slug: "kharagpur",
    state: "West Bengal",
    region: "India",
    famousFood: "South Indian tiffin, chaat, and campus snacks",
    seoDescription: "Kharagpur offers diverse pan-Indian dining driven by the historic railway and IIT campus cultures.",
  },
  {
    name: "Darjeeling",
    slug: "darjeeling",
    state: "West Bengal",
    region: "India",
    famousFood: "Darjeeling tea, momos, thukpa, and churpee",
    seoDescription: "Darjeeling is world-famous for the Champagne of Teas, authentic Tibetan steamed dumplings, and Himalayan views.",
  },
  {
    name: "Haldia",
    slug: "haldia",
    state: "West Bengal",
    region: "India",
    famousFood: "Fresh coastal hilsa, prawn malai curry, and crabs",
    seoDescription: "Haldia at the confluence of the Hooghly and Haldi rivers is renowned for fresh seasonal hilsa and coastal seafood.",
  },
];

// Precomputed O(1) Hash Maps and Adjacency Lists
const cityBySlugMap = new Map<string, CityPlace>();
const cityByNameMap = new Map<string, CityPlace>();
const citiesByStateMap = new Map<string, CityPlace[]>();

for (const city of cityPlaces) {
  const sSlug = city.slug.toLowerCase().trim();
  const sName = city.name.toLowerCase().trim();
  cityBySlugMap.set(sSlug, city);
  cityByNameMap.set(sName, city);

  if (city.state) {
    const stKey = city.state.toLowerCase().trim();
    let stateList = citiesByStateMap.get(stKey);
    if (!stateList) {
      stateList = [];
      citiesByStateMap.set(stKey, stateList);
    }
    stateList.push(city);
  }
}

/**
 * Constant-time O(1) lookup of a static city place by slug.
 */
export const getCityBySlug = (slug: string): CityPlace | undefined => {
  if (!slug) return undefined;
  return cityBySlugMap.get(slug.toLowerCase().trim());
};

/**
 * Constant-time O(1) lookup of a static city place by name.
 */
export const getCityByName = (name: string): CityPlace | undefined => {
  if (!name) return undefined;
  return cityByNameMap.get(name.toLowerCase().trim());
};

/**
 * Constant-time O(1) retrieval of all static cities belonging to a state.
 */
export const getCitiesByState = (stateName: string): CityPlace[] => {
  if (!stateName) return [];
  return citiesByStateMap.get(stateName.toLowerCase().trim()) ?? [];
};
